### ISSUE TITLE
Error on output reference

### ISSUE THREAD

**Issue by igorGevaerd** [fsdrw08/helm-charts#5]
When we try to deploy `powerdns` just by following what's described on `README.md`, this happens:
```bash
$ helm repo add fsdrw08 https://fsdrw08.github.io/helm-charts/
$ helm install powerdns fsdrw08/powerdns
Error: template: powerdns/templates/NOTES.txt:8:39: executing "powerdns/templates/NOTES.txt" at <.Values.service.type>: wrong type for value; expected string; got interface {}
```

This problem seems to be related to the `charts/powerdns/templates/NOTES.txt` file since it has a wrong reference to the possible values.

**Comment by fsdrw08** [comment]
Thanks for your fixing, chart updated
